// ════════════════════════════════════════════════════════════════════════════
// yara-rules-coverage.spec.ts — Per-rule coverage regression net.
//
// Reads `yara-rules-fired.json` (regenerated by
// `scripts/gen_yara_coverage.py`) and asserts that every (anchor,
// rule) pair the corpus once produced still produces those rules.
//
// Why this exists alongside `snapshot-matrix.spec.ts`:
//
//   The matrix pins at most three "family-anchor" rules per fixture
//   (intentional — pinning the long tail invites churn). That leaves
//   ~50 rules across the corpus that *do* fire but aren't pinned by
//   the matrix and could silently stop firing. This spec closes the
//   gap by inverting the relationship: for every rule, load its
//   first-anchor fixture and confirm the rule appears in the rule
//   set.
//
// Each anchor fixture is loaded ONCE per spec run (a single test per
// anchor, asserting the full subset of "rules-anchored-here"). With
// ~56 anchor fixtures across 187 fired rules this stays well inside
// the e2e wall-time budget.
//
// Unanchored rules are documentation only — see
// `yara-rules-fired.json:unanchoredRules`. CI does NOT block on
// growing that list (the corpus is a living document).
// ════════════════════════════════════════════════════════════════════════════

import * as fs from 'fs';
import * as path from 'path';
import { test, expect } from '@playwright/test';
import {
  REPO_ROOT,
  gotoBundle,
  loadFixture,
  ruleNames,
} from '../helpers/playwright-helpers';

interface CoverageManifest {
  summary: {
    totalRulesDefined: number;
    rulesFiredInCorpus: number;
    rulesUnanchored: number;
    anchorFixtures: number;
  };
  anchorFixtures: Record<string, string[]>;
  unanchoredRules: string[];
}

function loadManifest(): CoverageManifest {
  const p = path.join(REPO_ROOT, 'tests', 'e2e-fixtures', 'yara-rules-fired.json');
  if (!fs.existsSync(p)) {
    throw new Error(
      `${p} missing — regenerate with python scripts/gen_yara_coverage.py`);
  }
  return JSON.parse(fs.readFileSync(p, 'utf-8'));
}

const MANIFEST = loadManifest();

test.describe.configure({ mode: 'serial' });

test.describe('YARA rule coverage (per-anchor)', () => {
  test.beforeEach(async ({ page }) => {
    await gotoBundle(page);
  });

  // One test per anchor fixture. The test loads the anchor and
  // asserts that EVERY rule the manifest claims this anchor covers
  // is in the post-load rule set. A regression where one anchored
  // rule stops firing names the (anchor, rule) pair in the failure.
  for (const [anchor, rules] of Object.entries(MANIFEST.anchorFixtures)) {
    test(`${anchor} covers ${rules.length} rules`, async ({ page }) => {
      const findings = await loadFixture(page, anchor);
      const seen = ruleNames(findings);
      const missing: string[] = [];
      for (const r of rules) {
        if (!seen.includes(r)) missing.push(r);
      }
      expect(
        missing,
        `${anchor}: rules expected to fire but didn't: ${missing.join(', ')}`,
      ).toEqual([]);
    });
  }
});

// One stand-alone documentation test that exposes the coverage
// summary in the test log. Always passes — it's purely informational.
// (Playwright reports the test name + a short status; the
// `console.log` is captured under `test-results/`.)
test('YARA rule coverage summary (informational)', () => {
  const s = MANIFEST.summary;
  console.log(
    `[yara-coverage] defined=${s.totalRulesDefined} `
    + `fired=${s.rulesFiredInCorpus} `
    + `unanchored=${s.rulesUnanchored} `
    + `anchors=${s.anchorFixtures}`);
  // Sanity: at least 30% of defined rules must have fixture
  // coverage. Below that we've either shipped a rules-pack regression
  // or the corpus has decayed — either way, manual investigation.
  const pct = MANIFEST.summary.rulesFiredInCorpus
    / Math.max(1, MANIFEST.summary.totalRulesDefined);
  expect(pct).toBeGreaterThan(0.30);
});
